@echo off
pip install appdirs && ^
pip install catboost && ^
pip install certifi && ^
pip install charset-normalizer && ^
pip install combo && ^
pip install contourpy && ^
pip install cycler && ^
pip install filelock && ^
pip install fonttools && ^
pip install fsspec && ^
pip install graphviz && ^
pip install idna && ^
pip install Jinja2 && ^
pip install joblib && ^
pip install kiwisolver && ^
pip install lightgbm && ^
pip install llvmlite && ^
pip install lxml && ^
pip install markdown-it-py && ^
pip install MarkupSafe && ^
pip install matplotlib && ^
pip install mdurl && ^
pip install mpmath && ^
pip install networkx && ^
pip install numba && ^
pip install numpy && ^
pip install nvidia-cublas-cu12 && ^
pip install nvidia-cuda-cupti-cu12 && ^
pip install nvidia-cuda-nvrtc-cu12 && ^
pip install nvidia-cuda-runtime-cu12 && ^
pip install nvidia-cudnn-cu12 && ^
pip install nvidia-cufft-cu12 && ^
pip install nvidia-curand-cu12 && ^
pip install nvidia-cusolver-cu12 && ^
pip install nvidia-cusparse-cu12 && ^
pip install nvidia-nccl-cu12 && ^
pip install nvidia-nvjitlink-cu12 && ^
pip install nvidia-nvtx-cu12 && ^
pip install packaging && ^
pip install pandas && ^
pip install pillow && ^
pip install plotly && ^
pip install Pygments && ^
pip install pyod && ^
pip install pyparsing && ^
pip install pyshark && ^
pip install python-dateutil && ^
pip install pytz && ^
pip install requests && ^
pip install rich && ^
pip install scikit-learn && ^
pip install scipy && ^
pip install six && ^
pip install sympy && ^
pip install tenacity && ^
pip install termcolor && ^
pip install threadpoolctl && ^
pip install torch && ^
pip install tqdm && ^
pip install triton && ^
pip install typing_extensions && ^
pip install tzdata && ^
pip install urllib3 && ^
pip install xgboost